print("Corona Circular")
radio_ma = float(input(Ingresa radio mayor: "))
radio_me = float(input(Ingresa radio menor: "))
area = 3.14 * (radio_ma ** 2 - radio_me ** 2)
print("Resultados")
print("Área: ", area)
